# Generated by Django 3.0.2 on 2020-12-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hit_record_app', '0003_auto_20201025_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='dan',
            field=models.CharField(choices=[('初段', '初段'), ('弐段', '弐段'), ('参段', '参段'), ('四段', '四段'), ('五段', '五段'), ('錬士五段', '錬士五段'), (
                '錬士六段', '錬士六段'), ('教士六段', '教士六段'), ('教士七段', '教士七段'), ('教士八段', '教士八段'), ('範士八段', '範士八段')], max_length=255, verbose_name='称号段位'),
        ),
    ]
