# Generated by Django 3.1.4 on 2021-03-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hit_record_app', '0005_auto_20201220_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='hit',
            name='x_table',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='テーブル上x座標'),
        ),
        migrations.AddField(
            model_name='hit',
            name='y_table',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='テーブル上y座標'),
        ),
    ]
