@startuml er_diagram

' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

entity "大会テーブル（competition_tbl）" as competition_tbl {
  *competition_id : serial NOT NULL PRIMARY KEY UNIQUE
  --
  competition_name : text
  competition_type : text
}

entity "試合テーブル（match_tbl）" as match_tbl {
  *match_id : serial NOT NULL PRIMARY KEY UNIQUE
  --
  *competition_id : <<FK>>
  match_name : text
}

entity "的中記録テーブル（kyudo_tbl）" as hit_record_tbl {
  *record_id : serial NOT NULL PRIMARY KEY UNIQUE
  --
  *competition_id : <<FK>>
  *match_id : <<FK>>
  *player_id : text <<FK>>
  hit_record : text
}

entity "選手テーブル（player_tbl）" as player_tbl {
  *player_id : serial NOT NULL PRIMARY KEY UNIQUE
  --
  *competition_id : <<FK>>
  player_name : text
  team_name : text
  dan : text
  rank : text
}

competition_tbl ---o{ match_tbl
match_tbl ---o{ hit_record_tbl
player_tbl ---o{ hit_record_tbl
competition_tbl ---o{ hit_record_tbl
competition_tbl ---o{ player_tbl

@enduml