# Generated by Django 3.1.4 on 2020-12-20 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20201206_1604'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='hit',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.competition', verbose_name='大会'),
        ),
        migrations.AlterField(
            model_name='hit',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.match', verbose_name='試合'),
        ),
        migrations.AlterField(
            model_name='hit',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.player', verbose_name='選手'),
        ),
        migrations.AlterField(
            model_name='match',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='cms.competition', verbose_name='大会'),
        ),
        migrations.AlterField(
            model_name='player',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.competition', verbose_name='大会'),
        ),
    ]
