# Generated by Django 3.1.4 on 2021-03-07 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hit_record_app', '0006_auto_20210307_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hit',
            name='y_table',
        ),
    ]
